### ISSUE TITLE
outdated musl binary

### ISSUE THREAD

**Issue by Mylloon** [androzdev/mediaplex#9]
hello, I don't know if it is the right place to report this issue but the mediaplex-linux-x64-musl isn't updated (0.0.1 instead of 0.0.9)

this issue mean that mediaplex doesn't work when running on alpine

Edit: musl removed here: https://github.com/androzdev/mediaplex/pull/4

**Comment by twlite** [comment]
https://github.com/androzdev/mediaplex/releases/tag/v1.0.0
